spring:
  application:
    name: inventory-bk
  datasource:
    url: jdbc:h2:file:./data/inventory-db
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: # Leave empty if no password
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 5m

logging:
  level:
    org:
      springframework:
        web: Error
        jdbc: Error

system:
  userid: 9999

firebase:
  signUpBaseUrl: https://identitytoolkit.googleapis.com/v1/accounts:signUp
